name: run-backtest

on:
  workflow_dispatch:    # allow manual trigger
  schedule:
    - cron: '0 2 * * *'   # runs daily at 02:00 UTC (7:30 AM IST)

jobs:
  backtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install openpyxl   # for saving Excel files

      - name: Run backtest
        run: |
          python backtest.py

      - name: Convert CSV to Excel
        run: |
          python - <<EOF
          import pandas as pd
          df = pd.read_csv("backtest_results.csv")
          df.to_excel("backtest_results.xlsx", index=False, engine="openpyxl")
          EOF

      - name: Upload backtest results
        uses: actions/upload-artifact@v4
        with:
          name: backtest-output
          path: |
            backtest_results.xlsx
            equity_curve.png
